### ISSUE TITLE
Message AttachCustomMessageIdListener Stored in DB Not Same As MessageID Sent from Mailgun

### ISSUE THREAD

**Issue by mprythero** [stefanzweifel/laravel-sends#3]
Prior to using the `AttachCustomMessageIdListener` the message id wouldn't save in the database, but when using the `AttachCustomMessageIdListener`, the message id saved in the database is not the same as the one found in Mailgun.

Currently, the message ids found on Mailgun all end with @swift.generated but the numbers before the '@' are not similar to the ones stored in the sends database.

**Comment by stefanzweifel** [comment]
Yeah, that's by design. But the name `message_id` is probably the confusing part and the mistake on my part here.

I extracted this package from a project I'm working on. The project uses AWS SES to send emails. SES generates a unique Id in the `X-Ses-Message-ID` header. In the project, we stored that value in a `transport_message_id` column.
In this package, I've renamed this to `message_id`.

But I see now, how this makes understanding the package confusing. Message IDs have their own [RFC](https://datatracker.ietf.org/doc/html/rfc2392) with a specified schema. I'm just generating a UUID and call it a Message ID. 🙃 

Technically it could be possible to store the Message ID of your email provider. You could update `SENDS_HEADERS_CUSTOM_MESSAGE_ID` to `Message-ID`. (See [config](https://github.com/stefanzweifel/laravel-sends/blob/7887f49f9d7031be53ab697d66d12f27563140c9/config/sends.php#L13))
You then won't have to use `AttachCustomMessageIdListener` at all.

We could even make this the default, as the Symfony mailer used by Laravel always sets a `Message-ID` Header:
https://github.com/symfony/mailer/blob/6.0/SentMessage.php#L42

However, I will probably rename the column to something different in the coming days. Maybe `send_uuid`? 
The goal of the current `message_id` column is to be a separate unique ID that is generated **in** the Laravel app, and not by the email provider/Symfony.
Will provide upgrade instructions in an `UPGRADE.md` file, once v1.0 has been tagged.

Feebacks is grately appreciated.

---

As you're one who already uses the package – without a v1.0 being tagged – I have a question for you:

**How do you currently associate sends with a model?** 

- Do you use [the explicit way](https://github.com/stefanzweifel/laravel-sends#associate-sends-with-related-models) of passing an array of models to `associateWith([$this->product])`?
- Do you use [the implicit way](https://github.com/stefanzweifel/laravel-sends#automatically-associate-models-with-mailables), where the package uses the public properties?

I personally like the explicit way more, as logic is not hidden from me when reading the code. Therefore I would like to remove the implicit way of checking the public properties or at add a new `associateWithPublicProperties()` method, before tagging a v1.0 of the package.

**Comment by mprythero** [comment]
Ah, that does make a lot of sense. I see where you were going with that and I will definitely go with the current route of updating `SENDS_HEADERS_CUSTOM_MESSAGE_ID`. 

This is actually a really helpful utility, I have been looking for options and had been planning for some time doing something similar on my own before I found yours. 

I like the idea of separating the two, the only reason I currently need them separated is because I later use that message ID in conjunction with webhooks to track usage details regarding each email sent out. I do like the option though as I have been looking into utilizing AWS SES, just haven't gotten around to it.

I currently use the explicit way, in my mind it helps keep everything a bit more organized. However, I do like that you included it as it does provide a very beneficial option for those who have a different style of coding who prefer to cut as much extra from their classes and other files as much as possible.

**Comment by stefanzweifel** [comment]
> I like the idea of separating the two, the only reason I currently need them separated is because I later use that message ID in conjunction with webhooks to track usage details regarding each email sent out. I do like the option though as I have been looking into utilizing AWS SES, just haven't gotten around to it.

That's the exact same usage for me too and that's why I will keep them separate. By generating the ID on our own, we are more in control. Besides, I think `Message-ID` differs when sending mails as CC or BCC. That could lead to chaos when you later deal with webhooks.

---

> I currently use the explicit way, in my mind it helps keep everything a bit more organized. However, I do like that you included it as it does provide a very beneficial option for those who have a different style of coding who prefer to cut as much extra from their classes and other files as much as possible.

Thanks for the feedback! I will keep the "magic" in then :)

**Comment by stefanzweifel** [comment]
Quick update:

- `message_id`/`custom_message_id` has been renamed to `uuid`/`send_uuid` in #5 
- I've tagged [`v1.0.0`](https://github.com/stefanzweifel/laravel-sends/releases/tag/v1.0.0) of the package
- An [upgrade guide](https://github.com/stefanzweifel/laravel-sends/blob/main/UPGRADING.md#from-v01-to-v10) has been published to help anyone using the package to quickly migrate from `v0.1` to `v1.0`

Thanks again for your feedback!
